Repository felangel/cubit, pull requests merged in 2020-07, with the labels that each got.

#37 feat(cubit): v0.1.0
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
Labels: documentation, enhancement

#38 feat(angular_cubit): v0.1.0.dev.1
  packages/angular_cubit/CHANGELOG.md
  packages/angular_cubit/pubspec.yaml
Labels: enhancement

#39 feat(cubit_test): v0.1.0
  packages/cubit_test/CHANGELOG.md
  packages/cubit_test/pubspec.yaml
Labels: enhancement

#40 feat(flutter_cubit): v0.1.0
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/example/pubspec.yaml
  packages/flutter_cubit/lib/src/cubit_builder.dart
  packages/flutter_cubit/lib/src/cubit_consumer.dart
  packages/flutter_cubit/lib/src/cubit_listener.dart
  packages/flutter_cubit/lib/src/cubit_provider.dart
  packages/flutter_cubit/lib/src/multi_cubit_listener.dart
  packages/flutter_cubit/lib/src/multi_cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_builder_test.dart
  packages/flutter_cubit/test/cubit_listener_test.dart
Labels: documentation, enhancement

#47 feat(replay_cubit)!: ReplayMixin
  packages/replay_cubit/CHANGELOG.md
  packages/replay_cubit/README.md
  packages/replay_cubit/example/ios/Flutter/Debug.xcconfig
  packages/replay_cubit/example/ios/Flutter/Release.xcconfig
  packages/replay_cubit/example/ios/Podfile
  packages/replay_cubit/example/ios/Podfile.lock
  packages/replay_cubit/example/ios/Runner.xcodeproj/project.pbxproj
  packages/replay_cubit/example/ios/Runner.xcworkspace/contents.xcworkspacedata
  packages/replay_cubit/example/lib/main.dart
  packages/replay_cubit/example/pubspec.yaml
  packages/replay_cubit/lib/src/replay_cubit.dart
  packages/replay_cubit/pubspec.yaml
  packages/replay_cubit/test/cubits/counter_cubit.dart
  packages/replay_cubit/test/replay_cubit_test.dart
Labels: enhancement

#48 Coping with "file being used by another process" errors
  packages/hydrated_cubit/pubspec.yaml
  packages/hydrated_cubit/test/hydrated_storage_test.dart
Labels: bug

#49 docs: add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#50 docs: add issue and pull_request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#53 fix(hydrated_bloc): support use alongside hive
  packages/hydrated_cubit/lib/src/hydrated_storage.dart
  packages/hydrated_cubit/test/hive_interference_test.dart
  packages/hydrated_cubit/test/hydrated_storage_test.dart
Labels: bug

#54 chore(hydrated_cubit): v0.1.1
  packages/hydrated_cubit/CHANGELOG.md
  packages/hydrated_cubit/pubspec.yaml
Labels: chore

#59 fix(angular_cubit): upgrade to cubit v0.1.2
  packages/angular_cubit/CHANGELOG.md
  packages/angular_cubit/pubspec.yaml
Labels: bug, revert

#61 fix(hydrated_cubit): retain data during migration
  packages/hydrated_cubit/CHANGELOG.md
  packages/hydrated_cubit/lib/src/hydrated_storage.dart
  packages/hydrated_cubit/pubspec.yaml
  packages/hydrated_cubit/test/hydrated_storage_test.dart
Labels: bug

#63 fix(cubit_test): handle breaking change in package:async
  packages/cubit_test/CHANGELOG.md
  packages/cubit_test/lib/src/when_listen.dart
  packages/cubit_test/pubspec.yaml
Labels: bug

#64 chore(angular_cubit): restrict meta version in dev_deps
  packages/angular_cubit/CHANGELOG.md
  packages/angular_cubit/pubspec.yaml
Labels: chore

#65 fix(flutter_cubit): upgrade to cubit v0.1.2
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/pubspec.yaml
Labels: bug

#68 docs(hydrated_cubit): inline documentation improvements
  packages/hydrated_cubit/CHANGELOG.md
  packages/hydrated_cubit/lib/src/hydrated_cubit.dart
  packages/hydrated_cubit/pubspec.yaml
Labels: documentation
