Repository felangel/cubit, pull requests merged in 2020-06, with the labels that each got.

#2 feat: cubit v0.0.2
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/counter_cubit.dart
Labels: enhancement

#3 feat: flutter_cubit v0.0.2
  .github/workflows/flutter_cubit.yaml
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/example/lib/main.dart
  packages/flutter_cubit/example/pubspec.yaml
  packages/flutter_cubit/lib/src/cubit_builder.dart
  packages/flutter_cubit/lib/src/cubit_listener.dart
  packages/flutter_cubit/lib/src/cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_builder_test.dart
  packages/flutter_cubit/test/cubit_listener_test.dart
  packages/flutter_cubit/test/cubit_provider_test.dart
Labels: enhancement

#4 feat!: cubit v0.0.3
  README.md
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/counter_cubit.dart
Labels: enhancement

#5 feat!: flutter_cubit v0.0.3
  .github/workflows/cubit.yaml
  .github/workflows/flutter_cubit.yaml
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/example/lib/main.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_builder_test.dart
  packages/flutter_cubit/test/cubit_listener_test.dart
  packages/flutter_cubit/test/cubit_provider_test.dart
Labels: enhancement

#8 feat: CubitConsumer, MultiCubitListener, and MultiCubitProvider
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/analysis_options.yaml
  packages/flutter_cubit/lib/flutter_cubit.dart
  packages/flutter_cubit/lib/src/cubit_consumer.dart
  packages/flutter_cubit/lib/src/multi_cubit_listener.dart
  packages/flutter_cubit/lib/src/multi_cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_builder_test.dart
  packages/flutter_cubit/test/cubit_consumer_test.dart
  packages/flutter_cubit/test/cubit_listener_test.dart
  packages/flutter_cubit/test/multi_cubit_listener_test.dart
  packages/flutter_cubit/test/multi_cubit_provider_test.dart
Labels: enhancement

#9 fix: hide CubitListenerSingleChildWidget and CubitProviderSingleChildWidget
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/lib/flutter_cubit.dart
  packages/flutter_cubit/lib/src/cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_provider_test.dart
Labels: bug

#11 feat: create cubit_test
  .github/workflows/cubit_test.yaml
  README.md
  assets/cubit_test_full
  assets/cubit_test_full.png
  packages/cubit_test/.gitignore
  packages/cubit_test/CHANGELOG.md
  packages/cubit_test/LICENSE
  packages/cubit_test/README.md
  packages/cubit_test/analysis_options.yaml
  packages/cubit_test/coverage_badge.svg
  packages/cubit_test/example/main.dart
  packages/cubit_test/lib/cubit_test.dart
  packages/cubit_test/lib/src/cubit_test.dart
  packages/cubit_test/lib/src/mock_cubit.dart
  packages/cubit_test/lib/src/when_listen.dart
  packages/cubit_test/pubspec.yaml
  packages/cubit_test/test/cubit_test_test.dart
  packages/cubit_test/test/helpers/async_counter_cubit.dart
  packages/cubit_test/test/helpers/complex_cubit.dart
  packages/cubit_test/test/helpers/counter_cubit.dart
  packages/cubit_test/test/helpers/delayed_counter_cubit.dart
  packages/cubit_test/test/helpers/helpers.dart
  packages/cubit_test/test/helpers/multi_counter_cubit.dart
  packages/cubit_test/test/helpers/side_effect_counter_cubit.dart
  packages/cubit_test/test/helpers/sum_cubit.dart
  packages/cubit_test/test/mock_cubit_test.dart
  packages/cubit_test/test/when_listen_test.dart
Labels: enhancement

#12 fix(flutter_cubit): use Cubit<Object> instead of Cubit<dynamic> in CubitProvider
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/lib/src/cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
Labels: enhancement

#13 refactor!: make cubit initial state a named parameter
  README.md
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/counter_cubit.dart
  packages/cubit/test/cubits/cubits.dart
  packages/cubit/test/cubits/seeded_cubit.dart
Labels: enhancement

#15 feat(cubit): allow initialState to be null
  packages/cubit/CHANGELOG.md
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
Labels: enhancement

#16 feat(cubit)!: ignore duplicate states
  packages/cubit/CHANGELOG.md
  packages/cubit/lib/src/cubit.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/seeded_cubit.dart
Labels: enhancement

#17 feat(cubit_test)!: upgrade to cubit ^0.0.6
  packages/cubit_test/CHANGELOG.md
  packages/cubit_test/pubspec.yaml
Labels: bug, enhancement

#18 feat(cubit): add onTransition
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/cubit.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/lib/src/cubit_stream.dart
  packages/cubit/lib/src/transition.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/counter_cubit.dart
  packages/cubit/test/transition_test.dart
Labels: enhancement

#20 feat(flutter_cubit): upgrade to cubit v0.0.7
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/lib/src/cubit_builder.dart
  packages/flutter_cubit/lib/src/cubit_consumer.dart
  packages/flutter_cubit/lib/src/cubit_listener.dart
  packages/flutter_cubit/lib/src/cubit_provider.dart
  packages/flutter_cubit/pubspec.yaml
Labels: enhancement

#22 feat(cubit)!: revert named initialState parameter to be required
  README.md
  assets/cubit.png
  assets/cubit_full.png
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/lib/src/cubit_stream.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_test.dart
  packages/cubit/test/cubits/counter_cubit.dart
  packages/cubit/test/cubits/seeded_cubit.dart
Labels: enhancement

#23 feat(flutter_cubit)!: upgrade to cubit v0.0.8
  assets/cubit.png
  assets/flutter_cubit.png
  assets/flutter_cubit_full.png
  packages/flutter_cubit/CHANGELOG.md
  packages/flutter_cubit/README.md
  packages/flutter_cubit/example/lib/main.dart
  packages/flutter_cubit/pubspec.yaml
  packages/flutter_cubit/test/cubit_builder_test.dart
  packages/flutter_cubit/test/cubit_consumer_test.dart
  packages/flutter_cubit/test/cubit_listener_test.dart
  packages/flutter_cubit/test/cubit_provider_test.dart
  packages/flutter_cubit/test/multi_cubit_listener_test.dart
  packages/flutter_cubit/test/multi_cubit_provider_test.dart
Labels: enhancement

#24 feat(cubit_test)!: upgrade to cubit v0.0.8
  assets/cubit_test_full.png
  packages/cubit_test/CHANGELOG.md
  packages/cubit_test/example/main.dart
  packages/cubit_test/pubspec.yaml
  packages/cubit_test/test/helpers/async_counter_cubit.dart
  packages/cubit_test/test/helpers/complex_cubit.dart
  packages/cubit_test/test/helpers/counter_cubit.dart
  packages/cubit_test/test/helpers/delayed_counter_cubit.dart
  packages/cubit_test/test/helpers/multi_counter_cubit.dart
  packages/cubit_test/test/helpers/side_effect_counter_cubit.dart
  packages/cubit_test/test/helpers/sum_cubit.dart
Labels: enhancement

#25 docs(cubit): improve cubit documentation and package description
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/pubspec.yaml
Labels: documentation

#26 feat(angular_cubit): create angular_cubit package
  .github/workflows/angular_cubit.yaml
  README.md
  assets/angular_cubit_full.png
  examples/angular_counter/.gitignore
  examples/angular_counter/README.md
  examples/angular_counter/analysis_options.yaml
  examples/angular_counter/lib/app_component.dart
  examples/angular_counter/lib/app_component.html
  examples/angular_counter/lib/src/counter_page/counter_cubit.dart
  examples/angular_counter/lib/src/counter_page/counter_page_component.css
  examples/angular_counter/lib/src/counter_page/counter_page_component.dart
  examples/angular_counter/lib/src/counter_page/counter_page_component.html
  examples/angular_counter/pubspec.lock
  examples/angular_counter/pubspec.yaml
  examples/angular_counter/web/favicon.png
  examples/angular_counter/web/index.html
  examples/angular_counter/web/main.dart
  examples/angular_counter/web/styles.css
  packages/angular_cubit/.gitignore
  packages/angular_cubit/CHANGELOG.md
  packages/angular_cubit/LICENSE
  packages/angular_cubit/README.md
  packages/angular_cubit/analysis_options.yaml
  packages/angular_cubit/coverage_badge.svg
  packages/angular_cubit/dart_test.yaml
  packages/angular_cubit/example/main.dart
  packages/angular_cubit/lib/angular_cubit.dart
  packages/angular_cubit/lib/src/cubit_pipe.dart
  packages/angular_cubit/pubspec.yaml
  packages/angular_cubit/test/cubit_pipe_test.dart
Labels: enhancement

#27 Clean up README files
  README.md
  packages/angular_cubit/README.md
  packages/cubit/README.md
  packages/cubit_test/README.md
  packages/flutter_cubit/README.md
Labels: documentation

#28 ci: fix lcov-cop path resolution
  .github/workflows/cubit.yaml
  .github/workflows/cubit_test.yaml
  .github/workflows/flutter_cubit.yaml
Labels: ci

#29 ci: update workflow names
  .github/workflows/angular_cubit.yaml
  .github/workflows/cubit.yaml
  .github/workflows/cubit_test.yaml
  .github/workflows/flutter_cubit.yaml
Labels: ci

#30 feat(cubit): add CubitObserver
  packages/cubit/CHANGELOG.md
  packages/cubit/README.md
  packages/cubit/example/main.dart
  packages/cubit/lib/cubit.dart
  packages/cubit/lib/src/cubit.dart
  packages/cubit/lib/src/cubit_observer.dart
  packages/cubit/pubspec.yaml
  packages/cubit/test/cubit_observer_test.dart
  packages/cubit/test/cubit_test.dart
Labels: enhancement

#32 feat(hydrated_cubit)!: v0.0.3
  packages/hydrated_cubit/CHANGELOG.md
  packages/hydrated_cubit/README.md
  packages/hydrated_cubit/example/lib/main.dart
  packages/hydrated_cubit/lib/src/hydrated_cubit.dart
  packages/hydrated_cubit/lib/src/hydrated_storage.dart
  packages/hydrated_cubit/pubspec.yaml
  packages/hydrated_cubit/test/hydrated_cubit_test.dart
  packages/hydrated_cubit/test/hydrated_storage_test.dart
Labels: enhancement
